export {
  StableTargetResolver,
  type CandidateWitness,
  type StableResolveResult,
  type TargetResolutionResult,
} from './douyin/resolver/StableTargetResolver.js';
export { PersonResolver } from './douyin/resolver/PersonResolver.js';
export { GroupResolver } from './douyin/resolver/GroupResolver.js';
export { DouyinTargetResolverPage } from './douyin/resolver/DouyinTargetResolverPage.js';
export type { ResolutionWitness } from './douyin/resolver/ResolutionWitness.js';
export {
  ResolverBudget,
  type ResolverCandidate,
  type ResolverDirectoryPort,
  type ResolverDirectoryWindow,
  type ResolverPageState,
  type ResolverRuntimeOwner,
} from './douyin/resolver/types.js';
export {
  BrowserSession,
  BrowserSessionError,
  type BrowserSessionHandle,
  type BrowserProcessTrackingOptions,
  type BrowserSessionOptions,
} from './browser/BrowserSession.js';
export {
  DEFAULT_BROWSER_LOCALE,
  DEFAULT_BROWSER_VIEWPORT,
  DEFAULT_TIMEZONE,
  resolveBrowserSessionConfig,
  type BrowserSessionConfig,
  type BrowserSessionEnvironment,
  type BrowserViewport,
} from './browser/config.js';
export {
  AuthDetectionError,
  AuthDetector,
  AccountIdentityExtractionError,
  AccountOnboardingDetector,
  DouyinAccountIdentityExtractor,
  ContactResolver,
  DOUYIN_CHAT_URL,
  DouyinChatPage,
  DouyinChatPageError,
  MessageSender,
  MessageSenderError,
  ALLOW_REAL_SEND_ENV,
  TARGET_DISPLAY_NAME_ENV,
  TEST_MESSAGE_ENV,
  normalizeDisplayName,
  resolveTargetContactIdentity,
  resolveMessageSendRuntimeConfig,
  type AuthDetectionResult,
  type AuthDetectorOptions,
  type AuthStatus,
  type AccountIdentityExtractionErrorCode,
  type AccountOnboardingDetectionResult,
  type ChatReadinessResult,
  type ContactConversationSource,
  type ContactResolveResult,
  type ContactResolverOptions,
  type ContactTargetEnvironment,
  type ConversationCandidate,
  type ConversationListScrollResult,
  type ConversationOpenResult,
  type ConversationSummary,
  type DouyinChatErrorCode,
  type DouyinChatPageOptions,
  type DeliveryVerificationStatus,
  type MessageInputStatus,
  type MessageSendActionStatus,
  type MessageSendEnvironment,
  type MessageSendRequest,
  type MessageSendResult,
  type MessageSendRuntimeConfig,
  type MessageSendStatus,
  type MessageSenderErrorCode,
  type MessageSenderOptions,
  type ResolvedContact,
  type TargetContactIdentity,
} from './douyin/index.js';
export {
  DouyinContactDirectory,
  collectContactDirectory,
  type DirectoryResult,
  type DirectorySource,
  type DirectoryWindow,
} from './douyin/DouyinContactDirectory.js';
