export {
  BrowserSession,
  BrowserSessionError,
  type BrowserSessionHandle,
} from './browser/BrowserSession.js';
export {
  DEFAULT_BROWSER_LOCALE,
  DEFAULT_BROWSER_VIEWPORT,
  DEFAULT_TIMEZONE,
  resolveBrowserSessionConfig,
  type BrowserSessionConfig,
  type BrowserSessionEnvironment,
  type BrowserViewport,
} from './browser/config.js';
export {
  AuthDetectionError,
  AuthDetector,
  ContactResolver,
  DOUYIN_CHAT_URL,
  DouyinChatPage,
  DouyinChatPageError,
  TARGET_DISPLAY_NAME_ENV,
  normalizeDisplayName,
  resolveTargetContactIdentity,
  type AuthDetectionResult,
  type AuthDetectorOptions,
  type AuthStatus,
  type ChatReadinessResult,
  type ContactConversationSource,
  type ContactResolveResult,
  type ContactResolverOptions,
  type ContactTargetEnvironment,
  type ConversationCandidate,
  type ConversationListScrollResult,
  type ConversationOpenResult,
  type ConversationSummary,
  type DouyinChatErrorCode,
  type DouyinChatPageOptions,
  type ResolvedContact,
  type TargetContactIdentity,
} from './douyin/index.js';
