export {
  createDatabase,
  DatabaseClient,
  DATABASE_BUSY_TIMEOUT_MS,
  DATABASE_SYNCHRONOUS_MODE,
  DEFAULT_MIGRATIONS_DIRECTORY,
  openDatabaseReadOnly,
  ReadOnlyDatabaseClient,
  type CreateDatabaseOptions,
  type DatabaseColumnState,
  type DatabaseInspection,
  type DatabaseMigrationResult,
  type DatabasePragmaState,
} from './client/DatabaseClient.js';
export {
  DatabaseClientError,
  DatabaseInitializationError,
  DatabaseMigrationError,
  DatabaseSchemaError,
} from './client/errors.js';
export {
  DATA_DIR_ENV,
  DEFAULT_DATABASE_FILENAME,
  DEFAULT_DATA_DIRECTORY,
  resolveDatabasePath,
  type DatabaseEnvironment,
  type ResolveDatabasePathOptions,
} from './config/databaseConfig.js';
export {
  FRIEND_MATCH_FIELDS,
  FRIEND_MATCH_PRIORITY,
  FriendIdentityError,
  normalizeFriendIdentity,
  selectFriendMatch,
  type FriendMatch,
  type NormalizedFriendIdentity,
} from './identity/index.js';
export {
  executeMaintenanceCommand,
  MaintenanceCommandError,
  type AccountListMaintenanceOutput,
  type AccountMaintenanceOutput,
  type FriendListMaintenanceOutput,
  type FriendMaintenanceOutput,
  type MaintenanceOutput,
  type MessageTemplateListMaintenanceOutput,
  type MessageTemplateMaintenanceOutput,
  type ScheduleMaintenanceOutput,
} from './maintenance/MaintenanceCli.js';
export {
  V1ReleaseReadModel,
  type PreflightAccountState,
  type PreflightScheduleState,
  type PreflightTemplateState,
  type V1AuditDayData,
  type V1AuditSendRecordState,
  type V1AuditSystemEventState,
} from './readiness/V1ReleaseReadModel.js';
export {
  AccountRepository,
  AccountRepositoryError,
  type Account,
  type CreateAccountInput,
  type UpdateAccountInput,
  DEFAULT_DAILY_RUN_LIMIT,
  MAX_DAILY_RUN_LIMIT,
  DailyRunRepository,
  DailyRunRepositoryError,
  type CreateOrGetDailyRunInput,
  type ClaimDailyRunResult,
  type DailyRun,
  type DailyRunRepositoryErrorCode,
  type ListDailyRunsInput,
  FriendRepository,
  FriendRepositoryError,
  type CreateFriendInput,
  type Friend,
  type UpdateFriendInput,
  MessageTemplateDataError,
  MessageTemplateRepository,
  MessageTemplateRepositoryError,
  type CreateMessageTemplateInput,
  type UpdateMessageTemplateInput,
  NotificationConfigRepository,
  NotificationConfigRepositoryError,
  type NotificationConfig,
  type SaveNotificationConfigInput,
  ScheduleRepository,
  ScheduleRepositoryError,
  type CreateScheduleInput,
  type Schedule,
  type ScheduleRepositoryErrorCode,
  type UpdateScheduleInput,
  SendRecordRepository,
  SendRecordRepositoryError,
  type ClaimSendRecordResult,
  type PrepareSendRecordInput,
  type PrepareSendRecordResult,
  type RecoverInterruptedBeforeSendInput,
  type InterruptedRecoveryResult,
  type ScheduleRetryInput,
  type SendRecord,
  type SendRecordRepositoryErrorCode,
  DEFAULT_SYSTEM_EVENT_LIMIT,
  MAX_SYSTEM_EVENT_LIMIT,
  SystemEventRepository,
  SystemEventRepositoryError,
  type CreateSystemEventInput,
  type SystemEvent,
  AdminUserRepository,
  AdminUserRepositoryError,
  type AdminUser,
  type CreateAdminUserInput,
  type UpdateAdminUserInput,
  REPOSITORY_ERROR_CODES,
  RepositoryError,
  type RepositoryErrorCode,
  AdminSessionRepository,
  AdminSessionRepositoryError,
  type AdminSession,
  type CreateAdminSessionInput,
  AdminAuthRepository,
  AdminAuthRepositoryError,
  AUTH_DB_BUSY_TIMEOUT_MS,
  authAdminUserSelection,
  type AuthAdminUserRow,
  type BootstrapInitialAdminInput,
  type BootstrapInitialAdminResult,
  type CompleteAuthenticatedLoginInput,
  type CompleteAuthenticatedLoginResult,
  type ValidateSessionInput,
  type ValidateSessionResult,
  type LogoutCurrentSessionInput,
  type LogoutCurrentSessionResult,
  ACTIVE_LOGIN_SESSION_STATUSES,
  ALLOWED_LOGIN_SESSION_TRANSITIONS,
  TERMINAL_LOGIN_SESSION_STATUSES,
  AccountLoginSessionRepository,
  AccountLoginSessionRepositoryError,
  type AccountLoginSession,
  type CreateAccountLoginSessionInput,
  AvatarAssetRepository,
  AvatarAssetRepositoryError,
  type AvatarAsset,
  type CreateAvatarAssetInput,
  ContactSyncRunRepository,
  ContactSyncRunRepositoryError,
  type ContactSyncRun,
  type CreateContactSyncRunInput,
  type UpdateContactSyncRunInput,
  ALLOWED_PREFERRED_IDENTITY_KINDS,
  ContactRepository,
  ContactRepositoryError,
  type Contact,
  type CreateContactInput,
  type CreateContactWithPreferredIdentityInput,
  type InitialPreferredIdentityInput,
  type UpdateContactInput,
  ContactIdentityRepository,
  ContactIdentityRepositoryError,
  type ContactIdentity,
  type CreateContactIdentityInput,
  SendTaskRepository,
  SendTaskRepositoryError,
  type CreateSendTaskInput,
  type SendTask,
  type UpdateSendTaskInput,
  TERMINAL_EXECUTION_RUN_STATUSES,
  ExecutionRunRepository,
  ExecutionRunRepositoryError,
  type CreateExecutionRunInput,
  type ExecutionRun,
  TERMINAL_TARGET_SEND_STATUSES,
  TargetSendRecordRepository,
  TargetSendRecordRepositoryError,
  type ClaimTargetSendRecordResult,
  type CreateTargetSendRecordInput,
  type TargetSendRecord,
  DeliveryResolutionRepository,
  DeliveryResolutionRepositoryError,
  type CreateDeliveryResolutionInput,
  type DeliveryResolution,
  AuditEventRepository,
  AuditEventRepositoryError,
  type AuditEvent,
  type CreateAuditEventInput,
  LegacyBridgeRepository,
  LegacyBridgeRepositoryError,
  type LegacyFriendBinding,
  type LegacyScheduleImport,
} from './repositories/index.js';
export {
  accounts,
  dailyRuns,
  DAILY_RUN_STATUSES,
  friends,
  LOGIN_STATUSES,
  messageTemplates,
  notificationConfigs,
  schedules,
  sendRecords,
  SEND_RECORD_STATUSES,
  systemEvents,
  adminUsers,
  adminSessions,
  accountLoginSessions,
  avatarAssets,
  contactSyncRuns,
  contacts,
  contactIdentities,
  sendTasks,
  sendTaskTargets,
  executionRuns,
  targetSendRecords,
  deliveryResolutions,
  auditEvents,
  legacyFriendBindings,
  legacyScheduleImports,
  type AccountRow,
  type DailyRunRow,
  type FriendRow,
  type NewAccountRow,
  type NewDailyRunRow,
  type NewFriendRow,
  type MessageTemplateRow,
  type NewMessageTemplateRow,
  type NewNotificationConfigRow,
  type NotificationConfigRow,
  type NewScheduleRow,
  type NewSendRecordRow,
  type SendRecordRow,
  type ScheduleRow,
  type NewSystemEventRow,
  type SystemEventRow,
  type AdminUserRow,
  type NewAdminUserRow,
  type AdminSessionRow,
  type NewAdminSessionRow,
  type AccountLoginSessionRow,
  type NewAccountLoginSessionRow,
  type AvatarAssetRow,
  type NewAvatarAssetRow,
  type ContactSyncRunRow,
  type NewContactSyncRunRow,
  type ContactRow,
  type NewContactRow,
  type ContactIdentityRow,
  type NewContactIdentityRow,
  type SendTaskRow,
  type NewSendTaskRow,
  type SendTaskTargetRow,
  type NewSendTaskTargetRow,
  type ExecutionRunRow,
  type NewExecutionRunRow,
  type TargetSendRecordRow,
  type NewTargetSendRecordRow,
  type DeliveryResolutionRow,
  type NewDeliveryResolutionRow,
  type AuditEventRow,
  type NewAuditEventRow,
  type LegacyFriendBindingRow,
  type NewLegacyFriendBindingRow,
  type LegacyScheduleImportRow,
  type NewLegacyScheduleImportRow,
} from './schema/index.js';
export type {
  AccountLifecycleStatus,
  AccountLoginFailureCode,
  AccountLoginPurpose,
  AccountLoginSessionStatus,
  AccountProfileState,
  AdminUserStatus,
  AuditAction,
  AuditEntityType,
  AuditOutcome,
  BusinessDate,
  ContactAvailabilityStatus,
  ContactIdentityKind,
  ContactIdentitySource,
  ContactIdentityState,
  ContactIdentityStatus,
  ContactSyncFailureCode,
  ContactSyncRunStatus,
  ContactType,
  DailyRunStatus,
  DeliveryResolutionSource,
  DeliveryResolutionValue,
  ExecutionRunKind,
  ExecutionRunStatus,
  FriendIdentity,
  FriendMatchField,
  LegacyBindingStatus,
  LegacyScheduleImportStatus,
  MessageProviderType,
  MessageTemplate,
  RuntimeEventType,
  ScheduleTime,
  SendRecordStatus,
  SendTaskScheduleType,
  SystemEventLevel,
  TargetSendFailureCode,
  TargetSendMachineStatus,
} from '@sparkkeeper/shared';
