export {
  createDatabase,
  DatabaseClient,
  DATABASE_BUSY_TIMEOUT_MS,
  DATABASE_SYNCHRONOUS_MODE,
  DEFAULT_MIGRATIONS_DIRECTORY,
  openDatabaseReadOnly,
  ReadOnlyDatabaseClient,
  type CreateDatabaseOptions,
  type DatabaseColumnState,
  type DatabaseInspection,
  type DatabaseMigrationResult,
  type DatabasePragmaState,
} from './client/DatabaseClient.js';
export {
  DatabaseClientError,
  DatabaseInitializationError,
  DatabaseMigrationError,
  DatabaseSchemaError,
} from './client/errors.js';
export {
  DATA_DIR_ENV,
  DEFAULT_DATABASE_FILENAME,
  DEFAULT_DATA_DIRECTORY,
  resolveDatabasePath,
  type DatabaseEnvironment,
  type ResolveDatabasePathOptions,
} from './config/databaseConfig.js';
export {
  FRIEND_MATCH_FIELDS,
  FRIEND_MATCH_PRIORITY,
  FriendIdentityError,
  normalizeFriendIdentity,
  selectFriendMatch,
  type FriendMatch,
  type NormalizedFriendIdentity,
} from './identity/index.js';
export {
  executeMaintenanceCommand,
  MaintenanceCommandError,
  type AccountListMaintenanceOutput,
  type AccountMaintenanceOutput,
  type FriendListMaintenanceOutput,
  type FriendMaintenanceOutput,
  type MaintenanceOutput,
  type MessageTemplateListMaintenanceOutput,
  type MessageTemplateMaintenanceOutput,
  type ScheduleMaintenanceOutput,
} from './maintenance/MaintenanceCli.js';
export {
  V1ReleaseReadModel,
  type PreflightAccountState,
  type PreflightScheduleState,
  type PreflightTemplateState,
  type V1AuditDayData,
  type V1AuditSendRecordState,
  type V1AuditSystemEventState,
} from './readiness/V1ReleaseReadModel.js';
export {
  AccountRepository,
  AccountRepositoryError,
  type Account,
  type CreateAccountInput,
  type UpdateAccountInput,
  DEFAULT_DAILY_RUN_LIMIT,
  MAX_DAILY_RUN_LIMIT,
  DailyRunRepository,
  DailyRunRepositoryError,
  type CreateOrGetDailyRunInput,
  type ClaimDailyRunResult,
  type DailyRun,
  type DailyRunRepositoryErrorCode,
  type ListDailyRunsInput,
  FriendRepository,
  FriendRepositoryError,
  type CreateFriendInput,
  type Friend,
  type UpdateFriendInput,
  MessageTemplateDataError,
  MessageTemplateRepository,
  MessageTemplateRepositoryError,
  type CreateMessageTemplateInput,
  type UpdateMessageTemplateInput,
  NotificationConfigRepository,
  NotificationConfigRepositoryError,
  type NotificationConfig,
  type SaveNotificationConfigInput,
  ScheduleRepository,
  ScheduleRepositoryError,
  type CreateScheduleInput,
  type Schedule,
  type ScheduleRepositoryErrorCode,
  type UpdateScheduleInput,
  SendRecordRepository,
  SendRecordRepositoryError,
  type ClaimSendRecordResult,
  type PrepareSendRecordInput,
  type PrepareSendRecordResult,
  type RecoverInterruptedBeforeSendInput,
  type InterruptedRecoveryResult,
  type ScheduleRetryInput,
  type SendRecord,
  type SendRecordRepositoryErrorCode,
  DEFAULT_SYSTEM_EVENT_LIMIT,
  MAX_SYSTEM_EVENT_LIMIT,
  SystemEventRepository,
  SystemEventRepositoryError,
  type CreateSystemEventInput,
  type SystemEvent,
} from './repositories/index.js';
export {
  accounts,
  dailyRuns,
  DAILY_RUN_STATUSES,
  friends,
  LOGIN_STATUSES,
  messageTemplates,
  notificationConfigs,
  schedules,
  sendRecords,
  SEND_RECORD_STATUSES,
  type AccountRow,
  type DailyRunRow,
  type FriendRow,
  type NewAccountRow,
  type NewDailyRunRow,
  type NewFriendRow,
  type MessageTemplateRow,
  type NewMessageTemplateRow,
  type NewNotificationConfigRow,
  type NotificationConfigRow,
  type NewScheduleRow,
  type NewSendRecordRow,
  type SendRecordRow,
  type ScheduleRow,
  systemEvents,
  type NewSystemEventRow,
  type SystemEventRow,
} from './schema/index.js';
export type {
  BusinessDate,
  DailyRunStatus,
  FriendIdentity,
  FriendMatchField,
  MessageProviderType,
  MessageTemplate,
  ScheduleTime,
  SendRecordStatus,
  RuntimeEventType,
  SystemEventLevel,
} from '@sparkkeeper/shared';
